#!/usr/bin/env node
// =============================================================================
// tools/predictor_arena.mjs: replay each program's real branch stream through five predictors
//   docs/img/charts/predictor_arena.svg and predictor_arena.md
// =============================================================================
import fs from 'node:fs';
import { assemble } from '../model/asm.js';
import { Core, CONFIGS } from '../model/core.js';
import { runArena, branchTrace, PREDICTORS } from '../model/predictors.js';

const FONT = "font-family=\"'IBM Plex Sans','Segoe UI',Helvetica,Arial,sans-serif\"";
const MONO = "font-family=\"'IBM Plex Mono',Consolas,monospace\"";
const COLORS = { bht: '#9DB0B9', gshare: '#2E86C1', tournament: '#6A5ACD', perceptron: '#E08E0B', tage: '#27AE60' };
const pick = ['04_branch_penalty', '06_bubble_sort', '09_primes_sieve', '10_print_numbers', '11_gshare_patterns', '17_predictor_challenge'];
const rows = pick.map(name => {
  const img = assemble(fs.readFileSync(`programs/${name}.s`, 'utf8'));
  const trace = branchTrace(new Core(img, { ...CONFIGS.performance, bp: true }));
  return { name, branches: trace.length, results: runArena(trace) };
});
let md = `# Predictor arena (generated by tools/predictor_arena.mjs)\n\nFraction of conditional branches predicted correctly, replaying each program's real branch stream.\nBold = best.\n\n| program | branches | ${Object.values(PREDICTORS).map(C => C.label).join(' | ')} |\n|---|---:|${Object.keys(PREDICTORS).map(() => '---:').join('|')}|\n`;
for (const r of rows) { const best = Math.max(...r.results.map(x => x.accuracy)); md += `| ${r.name} | ${r.branches} | ${r.results.map(x => (x.accuracy === best ? `**${(100 * x.accuracy).toFixed(1)}%**` : `${(100 * x.accuracy).toFixed(1)}%`)).join(' | ')} |\n`; }
fs.writeFileSync('docs/img/charts/predictor_arena.md', md);
const W = 980, top = 80, gh = 104, lx = 220, bw = 620, H = top + rows.length * gh + 50;
let o = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"><rect width="100%" height="100%" rx="10" fill="#FBFCF8" stroke="#D5DBD0"/>`;
o += `<text x="16" y="28" ${FONT} font-size="17" font-weight="600" fill="#17251D">Predictor arena: the same branch streams, five predictors</text>`;
o += `<text x="16" y="48" ${FONT} font-size="12" fill="#4A5A50">Accuracy on each program's real branches. gshare and the tournament are in Sixfold's RTL; perceptron and TAGE are model-only (the families inside AMD Zen and other modern cores).</text>`;
const X = a => lx + bw * Math.max(0, (a - 0.4) / 0.6);
for (let a = 0.4; a <= 1.0001; a += 0.1) o += `<line x1="${X(a)}" x2="${X(a)}" y1="${top - 10}" y2="${top + rows.length * gh - 10}" stroke="#E3E8DF"/><text x="${X(a)}" y="${top - 14}" ${MONO} font-size="10" fill="#6B7A70" text-anchor="middle">${Math.round(a * 100)}%</text>`;
rows.forEach((r, j) => {
  const y0 = top + j * gh;
  o += `<text x="${lx - 12}" y="${y0 + 44}" ${MONO} font-size="12" fill="#17251D" text-anchor="end">${r.name}</text><text x="${lx - 12}" y="${y0 + 60}" ${FONT} font-size="10.5" fill="#6B7A70" text-anchor="end">${r.branches} branches</text>`;
  r.results.forEach((x, k) => {
    const y = y0 + k * 17;
    o += `<rect x="${lx}" y="${y}" width="${Math.max(1, X(x.accuracy) - lx)}" height="13" rx="2" fill="${COLORS[x.key]}"/><text x="${X(x.accuracy) + 5}" y="${y + 11}" ${MONO} font-size="10" fill="#4A5A50">${(100 * x.accuracy).toFixed(1)}%</text>`;
  });
});
let lxp = 16; const ly = H - 18;
for (const [k, C] of Object.entries(PREDICTORS)) { o += `<rect x="${lxp}" y="${ly - 10}" width="12" height="12" rx="2" fill="${COLORS[k]}"/><text x="${lxp + 17}" y="${ly}" ${FONT} font-size="11" fill="#4A5A50">${C.label}</text>`; lxp += 30 + C.label.length * 6.1; }
fs.writeFileSync('docs/img/charts/predictor_arena.svg', o + '</svg>\n');
console.log(md);
